#requires -Version 7.4
[CmdletBinding()]
param()

$ErrorActionPreference='Stop'
$validator=Join-Path $PSScriptRoot 'validate-contract.ps1'
$receiptGenerator=Join-Path $PSScriptRoot 'new-test-receipt.ps1'
$leafGenerator=Join-Path $PSScriptRoot 'new-native-leaf-summary.ps1'
$manifestGenerator=Join-Path $PSScriptRoot 'new-contract-manifest.ps1'
$references=Join-Path (Split-Path $PSScriptRoot -Parent) 'references'
$tempBase=[IO.Path]::GetTempPath()
$workspace=Join-Path $tempBase ("api-test-contract-"+[Guid]::NewGuid().ToString('n'))
$results=[ordered]@{}

function Ensure-Parent([string]$Path){$parent=Split-Path -Parent $Path;if(!(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}}
function Write-Json([string]$Path,$Value){Ensure-Parent $Path;[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 100)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Read-Json([string]$Path){Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json -Depth 100}
function Copy-Value($Value){$Value|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100}
function Get-Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Get-StringHash([string]$Value){$bytes=[Text.UTF8Encoding]::new($false).GetBytes($Value);[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant()}
function Get-DestinationFingerprint($d){Get-StringHash (('{0}|{1}|{2}|{3}|{4}|{5}|{6}|{7}|{8}|{9}|{10}' -f $d.id,$d.serviceId,$d.scheme,$d.host,$d.port,$d.basePath,$d.environmentClass,$d.networkScope,([bool]$d.allowRedirects).ToString().ToLowerInvariant(),([bool]$d.external).ToString().ToLowerInvariant(),([bool]$d.production).ToString().ToLowerInvariant())+"`n")}
function Expect-Reject([scriptblock]$Action){try{& $Action|Out-Null;$false}catch{$true}}

try{
    New-Item -ItemType Directory -Path $workspace|Out-Null
    $apiRoot=Join-Path $workspace 'api/openapi.json'
    Write-Json $apiRoot ([ordered]@{openapi='3.1.0';info=[ordered]@{title='contract';version='1'};paths=[ordered]@{'/healthz'=[ordered]@{get=[ordered]@{operationId='health-get'}};'/items'=[ordered]@{post=[ordered]@{operationId='item-create'}};'/provider'=[ordered]@{post=[ordered]@{operationId='provider-submit'}}}})
    $manifestPath=Join-Path $workspace '.api-test/contract-manifest.json'
    & $manifestGenerator -WorkspaceRoot $workspace -ContractId 'api-contract' -Format openapi -RootPath 'api/openapi.json' -FilePath @('api/openapi.json') -OutputPath $manifestPath|Out-Null
    $manifest=Read-Json $manifestPath
    $indexPath=Join-Path $workspace '.api-test/operation-index.json'
    $index=[ordered]@{schemaVersion='2.0';contractId='api-contract';serviceId='api';contractCombinedSha256=[string]$manifest.combinedSha256;operations=@(
        [ordered]@{id='health-get';method='GET';pathOrOperation='/healthz';effect='READ';external=$false;traceabilityKeys=@('health')},
        [ordered]@{id='item-create';method='POST';pathOrOperation='/items';effect='WRITE';external=$false;traceabilityKeys=@('item.create')},
        [ordered]@{id='provider-submit';method='POST';pathOrOperation='/provider';effect='WRITE';external=$true;traceabilityKeys=@('provider.submit')}
    )};Write-Json $indexPath $index
    $tracePath=Join-Path $workspace '.api-test/traceability.json'
    Write-Json $tracePath ([ordered]@{schemaVersion='2.0';contractId='api-contract';serviceId='api';mappings=@([ordered]@{businessOperationId='runtime.health';apiOperationIds=@('health-get')})})

    $destination=[ordered]@{id='api-local';serviceId='api';scheme='http';host='api';port=8080;basePath='/';environmentClass='test';networkScope='container-internal';allowRedirects=$false;external=$false;production=$false}
    $adapterPath=Join-Path $workspace 'project-adapter.json'
    $adapter=[ordered]@{schemaVersion='2.0';adapterVersion='0.1.0-rc.2';adapterId='contract-adapter';projectId='contract-project';framework='runner-neutral';roots=[ordered]@{workspace='.';source='api'};files=[ordered]@{scenarioRoot='.api-test/scenarios';catalog='.api-test/catalog.json'};candidateIdentity=[ordered]@{method='manifest-sha256';definitionRef='.api-test/source-identity.json';command=$null};serviceIdentity=[ordered]@{method='project-command';definitionRef='.api-test/service-identity.json';command=@('docker','inspect','api')};destinations=@($destination);contracts=@([ordered]@{id='api-contract';serviceId='api';format='openapi';manifest=[ordered]@{path='.api-test/contract-manifest.json';sha256=Get-Hash $manifestPath};operationIndex=[ordered]@{path='.api-test/operation-index.json';sha256=Get-Hash $indexPath};traceability=[ordered]@{path='.api-test/traceability.json';sha256=Get-Hash $tracePath}});runners=@([ordered]@{id='contract-runner';testTypes=@('smoke','negative','authorization','state','idempotency','integration');protocols=@('http');capabilities=@('http-request','status-assertion');argvTemplate=@('pwsh','-File','.api-test/runner.ps1','{requestPath}','{scenarioPath}','{evidencePath}');cwd='.';timeoutSeconds=60;envKeys=@('API_BASE_URL');mutationClass='TEST_OUTPUT'});supportedProtocols=@('http');capabilities=@('contract-manifest','operation-index','current-attestation');evidenceRoot='.local/evidence/api-tests';evidenceMode='GENERIC_CANONICAL';secretEnvKeys=@('API_TOKEN')}
    Write-Json $adapterPath $adapter

    $scenarioPath=Join-Path $workspace '.api-test/scenarios/health-smoke.json'
    $scenario=[ordered]@{schemaVersion='2.0';scenarioVersion='1.0.0';id='health-smoke';title='Health endpoint returns ready response';priority='P0';tags=@('smoke');testType='smoke';impact=[ordered]@{keys=@('operation:http:GET:/healthz','runtime:api-service');risk='local'};protocol='http';operations=@([ordered]@{id='health-get';contractId='api-contract';serviceId='api';method='GET';pathOrOperation='/healthz'});authentication=[ordered]@{mode='none';profileRef=$null;requiredScopes=@()};runtime=[ordered]@{runnerId='contract-runner';capabilities=@('http-request')};preconditions=@();fixture=[ordered]@{mode='none';reference=$null;ownsData=$false};permissions=[ordered]@{businessWrite=$false;testDataMutation=$false;externalCall=$false;productionAccess=$false;accountOrCredentialChange=$false};writePolicy=$null;steps=@([ordered]@{id='request-health';action='request';operationId='health-get';mutationClass='none';expectedObservation='one completed read response'});assertions=@([ordered]@{id='status-ready';kind='status';operator='equals';expected=200;sourceOfTruth='response';severity='REQUIRED';impactKeys=@('operation:http:GET:/healthz');evidenceTypes=@('response-metadata')});evidencePolicy=[ordered]@{bodyCapture='hash';redactHeaders=@('authorization','cookie');redactJsonPaths=@();artifacts=@()};stopConditions=@([ordered]@{id='unknown-outcome';condition='request outcome cannot be proven';classification='BLOCKED';detail='stop without replay'});timeBudgetSeconds=30}
    Write-Json $scenarioPath $scenario
    $catalogPath=Join-Path $workspace '.api-test/catalog.json'
    $catalog=[ordered]@{schemaVersion='2.0';catalogId='contract-catalog';catalogVersion='1.0.0';coveragePolicy=[ordered]@{mode='DECLARED_ACTIVE';activeOperationIds=@('health-get')};scenarios=@([ordered]@{id='health-smoke';path='.api-test/scenarios/health-smoke.json';sha256=Get-Hash $scenarioPath});relations=@()};Write-Json $catalogPath $catalog

    $sourceHash='a'*64;$diffHash='b'*64;$serviceHash='c'*64;$mutationHash='d'*64;$destinationHash=Get-DestinationFingerprint $destination
    $attestationPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/current-attestation.json'
    $attestation=[ordered]@{schemaVersion='2.0';attestationId='attestation-valid';observedAt=[DateTimeOffset]::UtcNow.ToString('o');candidate=[ordered]@{revision='candidate-1';sourceHash=$sourceHash;diffHash=$diffHash;buildId='build-1'};destination=[ordered]@{id='api-local';serviceId='api';fingerprint=$destinationHash};service=[ordered]@{serviceId='api';identityHash=$serviceHash};runtime=[ordered]@{kind='container';imageRef='sample-api:test';imageId='sha256:image-a';containerId='container-a';containerImageId='sha256:image-a';composeProject='contract-project'};contract=[ordered]@{contractId='api-contract';manifestHash=Get-Hash $manifestPath;combinedSha256=[string]$manifest.combinedSha256;operationIndexHash=Get-Hash $indexPath};authProfileFingerprint=$null;mutationStateHash=$mutationHash};Write-Json $attestationPath $attestation
    $requestPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/test-request.json'
    $request=[ordered]@{schemaVersion='2.0';requestId='request-valid';runId='run-valid';requestedAt=[DateTimeOffset]::UtcNow.ToString('o');authorizationRef='change-1:s2-r1';projectAdapter=[ordered]@{path='project-adapter.json';sha256=Get-Hash $adapterPath;adapterId='contract-adapter';adapterVersion='0.1.0-rc.2'};currentAttestation=[ordered]@{path='.local/evidence/api-tests/run-valid/current-attestation.json';sha256=Get-Hash $attestationPath};candidate=$attestation.candidate;environment=[ordered]@{name='contract-test';class='test';destinationId='api-local';destinationFingerprint=$destinationHash;serviceId='api';serviceIdentityHash=$serviceHash;contractId='api-contract';contractManifestHash=Get-Hash $manifestPath;contractCombinedSha256=[string]$manifest.combinedSha256;operationIndexHash=Get-Hash $indexPath;authProfileFingerprint=$null};run=[ordered]@{mode='BASELINE';parentReceipt=$null};testPlan=[ordered]@{catalog=[ordered]@{path='.api-test/catalog.json';sha256=Get-Hash $catalogPath;catalogId='contract-catalog';catalogVersion='1.0.0'};strategy='FULL';changedImpactKeys=@();upstreamDepth=0;downstreamDepth=0;fullSuiteTriggers=@('release-baseline');selectedScenarioIds=@('health-smoke')};authorization=[ordered]@{businessWrite=$false;testDataMutation=$false;externalCall=$false;productionAccess=$false;accountOrCredentialChange=$false};execution=[ordered]@{totalBudgetSeconds=60;maxParallelScenarios=1;isolatedRuntimePerScenario=$true;readRetryLimit=1;writeRetryLimit=0};output=[ordered]@{root='.local/evidence/api-tests/run-valid';evidenceFileName='evidence.json';receiptFileName='test-receipt.json';leafSummaryFileName='api-test-leaf-summary.json';overwrite=$false}};Write-Json $requestPath $request
    $evidencePath=Join-Path $workspace '.local/evidence/api-tests/run-valid/health-smoke/evidence.json'
    $evidence=[ordered]@{schemaVersion='2.0';evidenceId='evidence-health';requestId='request-valid';verdict='PASS';timing=[ordered]@{startedAt=[DateTimeOffset]::UtcNow.AddSeconds(-1).ToString('o');finishedAt=[DateTimeOffset]::UtcNow.ToString('o');durationMs=1000};scope=[ordered]@{requestHash=Get-Hash $requestPath;projectAdapterHash=Get-Hash $adapterPath;catalogHash=Get-Hash $catalogPath;scenarioId='health-smoke';scenarioHash=Get-Hash $scenarioPath;candidateSourceHash=$sourceHash;serviceIdentityHash=$serviceHash;destinationFingerprint=$destinationHash;contractManifestHash=Get-Hash $manifestPath;contractCombinedSha256=[string]$manifest.combinedSha256;operationIndexHash=Get-Hash $indexPath;attestationHash=Get-Hash $attestationPath;observedOperations=@('health-get')};preflight=[ordered]@{identityMatched=$true;destinationAllowed=$true;runnerAvailable=$true;authenticationAvailable=$true;fixtureReady=$true;runtimeHealthy=$true};runtime=[ordered]@{runnerId='contract-runner';protocol='http';commandHash='e'*64;serviceIdentityHash=$serviceHash;authProfileFingerprint=$null;attestationHash=Get-Hash $attestationPath;destinationId='api-local';destinationFingerprint=$destinationHash;finalDestinationFingerprint=$destinationHash;redirected=$false;imageRef='sample-api:test';imageId='sha256:image-a';containerId='container-a';containerImageId='sha256:image-a';composeProject='contract-project'};requests=@([ordered]@{id='request-1';operationId='health-get';method='GET';statusCode=200;durationMs=20;attempt=1;outcome='KNOWN';requestBodyHash=$null;responseBodyHash='f'*64;idempotencyKeyHash=$null;redactedFields=@()});steps=@([ordered]@{id='request-health';status='PASS';detail='health contract satisfied'});assertions=@([ordered]@{id='status-ready';kind='status';severity='REQUIRED';status='PASS';expected=200;actual=200;impactKeys=@('operation:http:GET:/healthz');evidenceRefs=@('request-1');findingFingerprint=$null});artifacts=@();mutations=@();excluded=@();blockers=@()};Write-Json $evidencePath $evidence

    foreach($schema in Get-ChildItem -LiteralPath $references -Filter '*.schema.json'){$null=Get-Content -LiteralPath $schema.FullName -Raw|ConvertFrom-Json -Depth 100};$results.AllSchemasParse=$true
    & $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $evidencePath -CurrentAttestationPath $attestationPath -RequireCurrentIdentity|Out-Null;$results.ValidCurrentIdentityPass=$?
    $nestedAdapter=Read-Json $adapterPath;$nestedAdapter.roots.workspace='..';$nestedAdapterPath=Join-Path $workspace '.api-test/project-adapter-nested.json';Write-Json $nestedAdapterPath $nestedAdapter
    $nestedRequest=Read-Json $requestPath;$nestedRequest.requestId='request-nested';$nestedRequest.runId='run-nested';$nestedRequest.projectAdapter.path='.api-test/project-adapter-nested.json';$nestedRequest.projectAdapter.sha256=Get-Hash $nestedAdapterPath;$nestedRequest.output.root='.local/evidence/api-tests/run-nested';$nestedRequestPath=Join-Path $workspace '.local/evidence/api-tests/run-nested/test-request.json';Write-Json $nestedRequestPath $nestedRequest
    & $validator -ProjectAdapterPath $nestedAdapterPath -RequestPath $nestedRequestPath|Out-Null;$results.ValidNestedAdapterWorkspace=$?
    $unboundedAdapter=Read-Json $nestedAdapterPath;$unboundedAdapter.roots.workspace='../../../../..';$unboundedAdapterPath=Join-Path $workspace '.api-test/project-adapter-unbounded.json';Write-Json $unboundedAdapterPath $unboundedAdapter
    $unboundedRequest=Read-Json $nestedRequestPath;$unboundedRequest.requestId='request-unbounded';$unboundedRequest.runId='run-unbounded';$unboundedRequest.projectAdapter.path='.api-test/project-adapter-unbounded.json';$unboundedRequest.projectAdapter.sha256=Get-Hash $unboundedAdapterPath;$unboundedRequest.output.root='.local/evidence/api-tests/run-unbounded';$unboundedRequestPath=Join-Path $workspace '.local/evidence/api-tests/run-unbounded/test-request.json';Write-Json $unboundedRequestPath $unboundedRequest
    $results.RejectUnboundedWorkspaceAncestor=Expect-Reject {& $validator -ProjectAdapterPath $unboundedAdapterPath -RequestPath $unboundedRequestPath}
    $outsideRequest=Read-Json $requestPath;$outsideRequest.requestId='request-outside-jail';$outsideRequest.runId='run-outside-jail';$outsideRequest.output.root='.local/other/run-outside-jail';$outsideRequestPath=Join-Path $workspace '.local/other/run-outside-jail/test-request.json';Write-Json $outsideRequestPath $outsideRequest
    $results.RejectOutputOutsideEvidenceJail=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $outsideRequestPath}
    $generated=& $receiptGenerator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $evidencePath|ConvertFrom-Json
    & $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $evidencePath -ReceiptPath ([string]$generated.receiptPath) -CurrentAttestationPath $attestationPath -RequireCurrentIdentity -RequireUnexpired|Out-Null;$results.ValidCanonicalReceipt=$?

    $drift=Read-Json $attestationPath;$drift.candidate.sourceHash='9'*64;$driftPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/drift-attestation.json';Write-Json $driftPath $drift
    $results.RejectCurrentSourceDrift=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $evidencePath -CurrentAttestationPath $driftPath -RequireCurrentIdentity}
    $imageDrift=Read-Json $attestationPath;$imageDrift.runtime.containerImageId='sha256:image-b';$imageDriftPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/image-drift.json';Write-Json $imageDriftPath $imageDrift
    $results.RejectImageContainerMismatch=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -CurrentAttestationPath $imageDriftPath -RequireCurrentIdentity}
    $targetDrift=Read-Json $requestPath;$targetDrift.environment.destinationFingerprint='8'*64;$targetDriftPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/target-drift.json';Write-Json $targetDriftPath $targetDrift
    $results.RejectDestinationDrift=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $targetDriftPath}
    $redirected=Read-Json $evidencePath;$redirected.runtime.redirected=$true;$redirected.runtime.finalDestinationFingerprint='7'*64;$redirectedPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/redirected.json';Write-Json $redirectedPath $redirected
    $results.RejectRedirectedDestination=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $redirectedPath}

    $originalBytes=[IO.File]::ReadAllBytes($apiRoot);[IO.File]::AppendAllText($apiRoot," `n",[Text.UTF8Encoding]::new($false))
    $results.RejectContractTamper=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath};[IO.File]::WriteAllBytes($apiRoot,$originalBytes)

    function Test-BadScenario($BadScenario,[string]$Name){
        $badScenarioPath=Join-Path $workspace ".api-test/scenarios/$Name.json";Write-Json $badScenarioPath $BadScenario
        $badCatalog=Read-Json $catalogPath;$badCatalog.scenarios=@([pscustomobject]@{id=[string]$BadScenario.id;path=".api-test/scenarios/$Name.json";sha256=Get-Hash $badScenarioPath});$badCatalog.coveragePolicy.activeOperationIds=@([string]$BadScenario.operations[0].id)
        $badCatalogPath=Join-Path $workspace ".api-test/$Name-catalog.json";Write-Json $badCatalogPath $badCatalog
        $badRequest=Read-Json $requestPath;$badRequest.requestId="request-$Name";$badRequest.runId="run-$Name";$badRequest.testPlan.catalog.path=".api-test/$Name-catalog.json";$badRequest.testPlan.catalog.sha256=Get-Hash $badCatalogPath;$badRequest.testPlan.selectedScenarioIds=@([string]$BadScenario.id);$badRequest.output.root=".local/evidence/api-tests/run-$Name"
        $badRequestPath=Join-Path $workspace ".local/evidence/api-tests/run-$Name/test-request.json";Write-Json $badRequestPath $badRequest
        Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $badRequestPath}
    }
    $badWrite=Read-Json $scenarioPath;$badWrite.id='bad-write';$badWrite.operations=@([pscustomobject]@{id='item-create';contractId='api-contract';serviceId='api';method='POST';pathOrOperation='/items'});$badWrite.steps[0].operationId='item-create';$badWrite.steps[0].mutationClass='none';$results.RejectPostMarkedNone=Test-BadScenario $badWrite 'bad-write'
    $badPoll=Copy-Value $badWrite;$badPoll.id='bad-poll';$badPoll.steps[0].action='poll';$badPoll.steps[0].mutationClass='business-write';$badPoll.permissions.businessWrite=$true;$badPoll.fixture=[pscustomobject]@{mode='project-fixture';reference='fixture-1';ownsData=$true};$badPoll.writePolicy=[pscustomobject]@{maxAttempts=1;automaticRetry=$false;idempotencyStrategy='operation-readback';compensation='restore'};$results.RejectPollOnWrite=Test-BadScenario $badPoll 'bad-poll'
    $badExternal=Copy-Value $badWrite;$badExternal.id='bad-external';$badExternal.operations=@([pscustomobject]@{id='provider-submit';contractId='api-contract';serviceId='api';method='POST';pathOrOperation='/provider'});$badExternal.steps[0].operationId='provider-submit';$badExternal.steps[0].mutationClass='business-write';$badExternal.permissions.businessWrite=$true;$badExternal.fixture=[pscustomobject]@{mode='project-fixture';reference='fixture-1';ownsData=$true};$badExternal.writePolicy=[pscustomobject]@{maxAttempts=1;automaticRetry=$false;idempotencyStrategy='not-supported-stop-on-unknown';compensation='none-stop-unresolved'};$results.RejectUnmarkedExternalCall=Test-BadScenario $badExternal 'bad-external'
    $badOperation=Read-Json $scenarioPath;$badOperation.id='bad-operation';$badOperation.operations[0].id='missing-operation';$badOperation.steps[0].operationId='missing-operation';$results.RejectMissingOperation=Test-BadScenario $badOperation 'bad-operation'

    $unknown=Read-Json $evidencePath;$unknown.requests[0].outcome='UNKNOWN';$unknownPath=Join-Path $workspace '.local/evidence/api-tests/run-valid/unknown.json';Write-Json $unknownPath $unknown
    $results.RejectPassWithUnknownOutcome=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -EvidencePath $unknownPath}

    $nativeAdapter=Read-Json $adapterPath;$nativeAdapter.evidenceMode='PROJECT_NATIVE_PARENT';$nativeAdapterPath=Join-Path $workspace 'project-adapter-native.json';Write-Json $nativeAdapterPath $nativeAdapter
    $nativeRequest=Read-Json $requestPath;$nativeRequest.requestId='request-native';$nativeRequest.runId='run-native';$nativeRequest.projectAdapter.path='project-adapter-native.json';$nativeRequest.projectAdapter.sha256=Get-Hash $nativeAdapterPath;$nativeRequest.output.root='.local/evidence/api-tests/run-native';$nativeRequestPath=Join-Path $workspace '.local/evidence/api-tests/run-native/test-request.json';Write-Json $nativeRequestPath $nativeRequest
    $nativeEvidence=Read-Json $evidencePath;$nativeEvidence.evidenceId='evidence-native';$nativeEvidence.requestId='request-native';$nativeEvidence.scope.requestHash=Get-Hash $nativeRequestPath;$nativeEvidence.scope.projectAdapterHash=Get-Hash $nativeAdapterPath;$nativeEvidencePath=Join-Path $workspace '.local/evidence/api-tests/run-native/health-smoke/evidence.json';Write-Json $nativeEvidencePath $nativeEvidence
    $leaf=& $leafGenerator -ProjectAdapterPath $nativeAdapterPath -RequestPath $nativeRequestPath -EvidencePath $nativeEvidencePath -CurrentAttestationPath $attestationPath|ConvertFrom-Json
    & $validator -ProjectAdapterPath $nativeAdapterPath -RequestPath $nativeRequestPath -EvidencePath $nativeEvidencePath -NativeLeafSummaryPath ([string]$leaf.summaryPath) -CurrentAttestationPath $attestationPath -RequireCurrentIdentity|Out-Null;$results.ValidProjectNativeLeaf=$?
    $results.RejectSecondParentForNativeMode=Expect-Reject {& $receiptGenerator -ProjectAdapterPath $nativeAdapterPath -RequestPath $nativeRequestPath -EvidencePath $nativeEvidencePath}
    $results.RejectMissingCurrentAttestation=Expect-Reject {& $validator -ProjectAdapterPath $adapterPath -RequestPath $requestPath -RequireCurrentIdentity}

    $failed=@($results.GetEnumerator()|Where-Object{-not [bool]$_.Value})
    [pscustomobject]$results|ConvertTo-Json
    if($failed.Count -gt 0){throw "Contract checks failed: $($failed.Name -join ', ')"}
}finally{
    $resolved=[IO.Path]::GetFullPath($workspace);$prefix=[IO.Path]::GetFullPath((Join-Path $tempBase 'api-test-contract-'))
    $comparison=if($IsWindows){[StringComparison]::OrdinalIgnoreCase}else{[StringComparison]::Ordinal}
    if($resolved.StartsWith($prefix,$comparison)-and(Test-Path -LiteralPath $resolved)){Remove-Item -LiteralPath $resolved -Recurse -Force}
}
